wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 4
iteration:
  value: 300
learning_rate:
  value: 0.0001328858052329497
model:
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
