wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 8
iteration:
  value: 300
learning_rate:
  value: 0.0009011198724676408
model:
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
