wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 2
iteration:
  value: 300
learning_rate:
  value: 0.00011031159375430456
model:
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
