wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 8
iteration:
  value: 5000
learning_rate:
  value: 0.0005925297258736013
model:
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
