wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 8
iteration:
  value: 5000
learning_rate:
  value: 0.0005815668921378718
model:
  value: COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml
