wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 4
iteration:
  value: 1000
learning_rate:
  value: 0.00014159608540783165
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
