wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 4
iteration:
  value: 1000
learning_rate:
  value: 0.0004961472994150497
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
