wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 2
iteration:
  value: 300
learning_rate:
  value: 0.00013771126011836543
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
