wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 4
iteration:
  value: 5000
learning_rate:
  value: 9.526833739813734e-05
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
