wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  desc: null
  value: 32
IMS_PER_BATCH:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659349717
    t:
      1:
      - 1
      - 41
      - 43
      - 55
      2:
      - 1
      - 41
      - 43
      - 55
      3:
      - 2
      4: 3.8.13
      5: 0.12.21
      8:
      - 5
iteration:
  desc: null
  value: 300
learning_rate:
  desc: null
  value: 0.00011031159375430456
model:
  desc: null
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
