wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 2
iteration:
  value: 1500
learning_rate:
  value: 0.0006152965382373505
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
