wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 8
iteration:
  value: 5000
learning_rate:
  value: 6.495101275852944e-05
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
