wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1500
learning_rate:
  value: 0.00018314742537202944
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
