wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 4
iteration:
  value: 5000
learning_rate:
  value: 0.0005944830264519745
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
