wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1500
learning_rate:
  value: 0.00022439065196111865
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
