wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 2
iteration:
  value: 300
learning_rate:
  value: 0.0001988329995060365
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
