wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1500
learning_rate:
  value: 0.00016547665002076474
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
