wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 2
iteration:
  value: 5000
learning_rate:
  value: 0.0006173877360072272
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
