wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1000
learning_rate:
  value: 0.00072513170475898
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
