wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1500
learning_rate:
  value: 0.000296148385569311
model:
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
