wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 8
iteration:
  value: 5000
learning_rate:
  value: 0.0008259195845859812
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
