wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 2
iteration:
  value: 1000
learning_rate:
  value: 0.0008635738005785306
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
