wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 2
iteration:
  value: 1500
learning_rate:
  value: 6.796871703698626e-05
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
