wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 4
iteration:
  value: 1000
learning_rate:
  value: 0.0008827309350055315
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
