wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 128
IMS_PER_BATCH:
  value: 8
iteration:
  value: 1000
learning_rate:
  value: 0.0006520443814103229
model:
  value: COCO-Detection/rpn_R_50_FPN_1x.yaml
