wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 4
iteration:
  value: 1000
learning_rate:
  value: 8.961698272171736e-05
model:
  value: COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml
