wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659338439
    t:
      1:
      - 1
      - 41
      - 43
      - 55
      2:
      - 1
      - 41
      - 43
      - 55
      3:
      - 2
      - 16
      4: 3.8.13
      5: 0.12.21
      8:
      - 5
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: total_loss
parameters:
  desc: null
  value:
    BATCH_SIZE_PER_IMAGE:
      values:
      - 32
      - 64
      - 128
      - 256
    IMS_PER_BATCH:
      values:
      - 2
      - 4
      - 8
    iteration:
      values:
      - 300
      - 1000
      - 1500
      - 5000
    learning_rate:
      distribution: uniform
      max: 0.001
      min: 0
    model:
      value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
