wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 64
IMS_PER_BATCH:
  value: 4
iteration:
  value: 300
learning_rate:
  value: 0.0008640952710331209
model:
  value: COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml
