wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 32
IMS_PER_BATCH:
  value: 4
iteration:
  value: 5000
learning_rate:
  value: 2.256714619165734e-05
model:
  value: COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml
