wandb_version: 1

BATCH_SIZE_PER_IMAGE:
  value: 256
IMS_PER_BATCH:
  value: 4
iteration:
  value: 1500
learning_rate:
  value: 0.00018531348332502103
model:
  value: COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml
